### ISSUE TITLE
Migrate from Newtonsoft.Json to System.Text.Json

### ISSUE THREAD

**Issue by yong7743** [Esri/arcgisearth-automation-api#28]
The `System.Text.Json` namespace provides functionality for serializing to and deserializing from JavaScript Object Notation (JSON). The `System.Text.Json` library is included in the runtime for [.NET Core 3.1](https://dotnet.microsoft.com/download/dotnet/3.1) and later versions. 
https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/migrate-from-newtonsoft

The System.Text.Json can meet our current requirements, we don't need to import a 3rd party library for JSON serializing and deserializing, and also can avoid some security alerts, e.g. 
![image](https://github.com/Esri/arcgisearth-automation-api/assets/9249205/055a96f9-7c4e-4547-8a83-cac235cdb99a)

**Comment by gis2all** [comment]
Fixed in PR https://github.com/Esri/arcgisearth-automation-api/pull/31
